input_basedir: "."

input:
  - name: "icons"

output_basedir: "export"
# WARNING: deletes all files within output directory if it exists
empty_output: true
format: "sprite"
retina: true
size_filter: 14

global_style:
  padding: 1
  fill: "#1a1a1a"

  halo:
    fill: "#ffffff"
    width: 1
    opacity: 0.3

sprite:
  cols: 12
  outer_padding: 0
  icon_padding: 4
  filename: "icons"
